const dogs = {
  Rex: {
    name: "Rex",
    avatar: "./images/dog-rex.jpg",
    age: 25,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  Bella: {
    name: "Bella",
    avatar: "./images/dog-bella.jpg",
    age: 43,
    bio: "Yup, that's my owner. U can meet him if you want",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  Teddy: {
    name: "Teddy",
    avatar: "./images/dog-teddy.jpg",
    age: 30,
    bio: "How you doin?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  Snake1: {
    name: "Snake1",
    avatar: "./images/snake1.png",
    age: 30,
    bio: "Slidering",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  Snake2: {
    name: "Snake2",
    avatar: "./images/snake2.png",
    age: 30,
    bio: "Slidering",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  Snake3: {
    name: "Snake3",
    avatar: "./images/snake3.png",
    age: 30,
    bio: "Slidering",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  Snake4: {
    name: "Snake4",
    avatar: "./images/snake4.png",
    age: 30,
    bio: "Slidering",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
};

export default dogs;
